# Generated by Django 3.1.4 on 2020-12-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yolo_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
